"""
AI Interface Prediction
========================

This module provides an abstraction for handling predictions in machine learning systems. It serves as
a bridge between AI models and higher-level systems, such as APIs, dashboards, or batch processing scripts.

License: MIT
Author: G.O.D Framework Team
"""

import logging
from typing import List, Any


class PredictionInterface:
    """
    A class for interfacing with a machine learning model to handle prediction requests.

    This class provides functionality for handling the complete lifecycle of prediction
    requests. It includes input preprocessing, generating predictions using the provided
    model, and postprocessing the prediction results. The class can be extended/customized
    for specific AI/ML models by overriding the relevant methods.

    :ivar model: The machine learning model used for generating predictions.
    :ivar logger: Logger instance used for asynchronous logging within the class.
    :type model: Any
    :type logger: logging.Logger
    """

    def __init__(self, model):
        """
        Initializes the PredictionInterface with a machine learning model.

        :param model: The AI/ML model used for generating predictions.
        """
        self.model = model
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.INFO)
        handler = logging.StreamHandler()
        handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
        self.logger.addHandler(handler)
        self.logger.info("PredictionInterface initialized successfully.")

    def handle_prediction_request(self, input_data: List[Any]) -> List[Any]:
        """
        Handles incoming prediction requests, applies preprocessing, and returns predictions.

        :param input_data: Data to generate predictions on (e.g., list of features).
        :return: Prediction results from the AI model.
        """
        self.logger.info("Handling prediction request...")

        # Preprocess the input
        try:
            self.logger.info("Preprocessing input data.")
            processed_data = self.preprocess_input(input_data)
        except Exception as e:
            self.logger.error(f"Preprocessing error: {str(e)}")
            raise ValueError("Invalid input data format.") from e

        # Generate predictions
        try:
            self.logger.info("Generating predictions...")
            predictions = self.generate_predictions(processed_data)
            self.logger.info(f"Predictions generated: {predictions}")
        except Exception as e:
            self.logger.error(f"Prediction error: {str(e)}")
            raise RuntimeError("Prediction process failed.") from e

        # Postprocess predictions
        predictions = self.postprocess_output(predictions)

        return predictions

    def preprocess_input(self, input_data: List[Any]) -> List[Any]:
        """
        Prepares input data in the required format for the model.
        Override this method for custom input preprocessing.

        :param input_data: Raw input data.
        :return: Preprocessed input data.
        """
        # Example: Ensure input is a list of floats or integers
        if not isinstance(input_data, list) or not all(isinstance(x, (int, float)) for x in input_data):
            raise TypeError("Input data must be a list of numeric values.")

        return input_data

    def generate_predictions(self, preprocessed_data: List[Any]) -> List[Any]:
        """
        Generates predictions using the underlying model.
        Override this method to integrate with custom models.

        :param preprocessed_data: Data prepared for prediction.
        :return: Predictions generated by the model.
        """
        # Mock prediction logic (for testing): double the input values
        return [x * 2 for x in preprocessed_data]

    def postprocess_output(self, predictions: List[Any]) -> List[Any]:
        """
        Processes the model's raw predictions into a user-friendly format.
        Override this method for custom post-processing.

        :param predictions: Raw predictions from the model.
        :return: Postprocessed predictions.
        """
        # Example: Convert to integers if required
        return predictions


# ===== Advanced Extensions =====

class ValidatingPredictionInterface(PredictionInterface):
    """
    Implements a prediction interface with input validation.

    This class provides a method to preprocess and validate input data
    ensuring it meets specific criteria before passing it to prediction
    mechanisms. It ensures that the input is a list of numeric, positive
    values, and logs the validation process.

    :ivar logger: Logger instance used for logging validation and other
                  information.
    :type logger: logging.Logger
    """

    def preprocess_input(self, input_data: List[Any]) -> List[Any]:
        self.logger.info("Validating input data.")
        # Ensure the list is numeric and positive
        if not isinstance(input_data, list):
            raise ValueError("Input must be a list.")
        if not all(isinstance(x, (int, float)) for x in input_data):
            raise TypeError("All input values must be numbers.")
        if not all(x >= 0 for x in input_data):
            raise ValueError("All input values must be non-negative.")
        self.logger.info("Input validation passed.")
        return input_data


class BatchPredictionInterface(PredictionInterface):
    """
    Provides functionality to handle batch prediction requests for multiple datasets.

    This class extends the PredictionInterface to introduce the ability to process several
    datasets simultaneously, returning predictions for each dataset in the batch.

    :ivar logger: Logger instance for recording batch prediction activities.
    :type logger: logging.Logger
    """

    def batch_predictions(self, batch_data: List[List[Any]]) -> List[List[Any]]:
        """
        Handles batch prediction requests for multiple datasets.

        :param batch_data: A list of input datasets for batch prediction.
        :return: List of predictions for each input dataset.
        """
        self.logger.info("Processing batch prediction requests...")
        try:
            all_predictions = [
                self.handle_prediction_request(dataset) for dataset in batch_data
            ]
            self.logger.info("Batch prediction completed successfully.")
            return all_predictions
        except Exception as e:
            self.logger.error(f"Batch prediction failed: {str(e)}")
            raise


# ===== Example Usage =====

if __name__ == "__main__":
    # Example 1: Mock Model Prediction
    print("===== Example 1: Mock Model Prediction =====")
    mock_model = None
    interface = PredictionInterface(mock_model)

    input_data = [1, 2, 3, 4, 5]
    predictions = interface.handle_prediction_request(input_data)
    print("Predictions:", predictions)

    # Example 2: Validated Input Prediction
    print("\n===== Example 2: Validated Input Prediction =====")
    validating_interface = ValidatingPredictionInterface(mock_model)

    try:
        validated_predictions = validating_interface.handle_prediction_request([1, -2, 3])
    except Exception as e:
        print(f"Validation failed: {e}")

    # Example 3: Batch Predication
    print("\n===== Example 3: Batch Predication =====")
    batch_interface = BatchPredictionInterface(mock_model)

    batch_data = [[1, 2, 3], [4, 5, 6]]
    batch_output = batch_interface.batch_predictions(batch_data)
    print("Batch Predictions:", batch_output)